spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/auth/**
            filters:
              - PrefixPath=/auth/v1

          - id: job-service
            uri: https://tpfz4s1t-8002.inc1.devtunnels.ms
            predicates:
              - Path=/job/**

        globalcors:
          cors-configurations:
            '[/**]':
              allowed-origins: "http://localhost:5173"
              allowed-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
              allowed-headers: "*"
              allow-credentials: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework: INFO
    com.talenta: DEBUG
